server:
  port: 8080
  servlet:
    contextPath: /mssivimss-oauth

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
            
  main:
    allow-circular-references: true
        
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
            
logging:
  level:
    root: info
    org.springframework.web: info
    org.hibernate: error

endpoints:
   dominio-consulta: http://localhost:8090/mssivimss-mod-catalogos

jwt:
  secretkey: funcionamuybienlogin
  secretkey-flujo: funcionamuybien
  secretkey-dominios: funcionamuybiendominio
  expiration-milliseconds: 360