server:
  port: 8082
  servlet:
    contextPath: /${spring.application.name}/v1

spring:
  application:
    name: mssivimss-oauth
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
      
  datasource:
    platform: mariadb
    driverClassName: org.mariadb.jdbc.Driver
    url: 'jdbc:mysql://10.250.10.47:3306/SIVIBDQA?useunicode=true&characterEncoding=utf-8&useJDBCCompilantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimeZone=America/Mexico_city'
    username: 'SIVIBDQA_USER'
    password: 'user_QASIVI'
    timeBetweenEvictionRunsMillis: 1000
    testWhileIdle: true
    validationQuery: SELECT 1
    hikari:
      max-lifetime:  1800000
      idle-timeout:  60000
      connection-timeout: 90000
      auto-commit: false
      maximum-pool-size:  8
      minimum-idle:  10

  main:
    allow-circular-references: true
    
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect:org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
           
logging:
  level:
    root: info
    org.springframework.web: info
    org.hibernate: error

endpoints:
   envio-correo: 'http://sivimss-qa.apps.ocp.imss.gob.mx/mssivimss-ser-externos/v1/catalogos/externos/enviar/correo/recuperacontrasenia'
   consulta-siap: 'http://serviciosdigitalesinterno-stage.imss.gob.mx/serviciosDigitales-rest/v1/externos/siap/matricula'
jwt:
  secretkey: funcionamuybienlogin
  secretkey-flujo: 'funcionamuybien'
  secretkey-dominios: funcionamuybiendominio
  expiration-milliseconds: 360
  
management:
      endpoints:
          web:
            exposure:
                include:
                    health,info,metrics

resilience4j.circuitbreaker:
    circuitBreakerAspectOrder: 1
    instances:
      msflujo:
        automaticTransitionFromOpenToHalfOpenEnabled: 'true'
        failureRateThreshold: 50
        slidingWindowType: COUNT_BASED
        event-consumer-buffer-size: '10'
        registerHealthIndicator: 'true'
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: '5'
resilience4j.retry:
    retryAspectOrder: 2
    instances:
        msflujo:
           maxAttempts: 3
           waitDuration: 5s
resilience4j.timelimiter:
    timeLimiterAspectOrder: 3
    instances:
      msflujo:
        timeout-duration: 3s
        
formato_fecha: '%d/%m/%Y'
formato_fecha_hora: '%d/%m/%Y %H:%i:%s'
patron_formato_fecha_hora: 'dd/MM/yyyy HH:mm:ss'
ruta-log: 'C:\Users\egarcial\Desktop\SIVIMSS\workspace\yo\mssivimss-oauth\'

tiempo-vida: 0
